### ISSUE TITLE
Reduce steps to opening most relevant repo's, branches, etc. 

### ISSUE THREAD

**Issue by loujaybee** [gitpod-samples/Gitpod-Raycast-Extension#19]
Can we reduce the number of steps to open a familiar repo? Possibly by moving some of the options from step 3 onto step 2, or maybe even into the main search page of Raycast? To open a repo I have to: 

1. Type "Gitpod"
2. Select a repo
3. Select a context

Is there any way we could bring useful recent contexts to the 2nd, or even 1st page? So that I've got my "recently" used or most frequently used contexts more accessible? 💭 🤔 

|Step 1|Step 2|Step 3|
|-|-|-|
|<img width="759" alt="image" src="https://user-images.githubusercontent.com/5528307/218062306-1b803779-8eb0-4ca8-8eea-a983c6b216cc.png">|<img width="771" alt="image" src="https://user-images.githubusercontent.com/5528307/218062437-d59cea8c-4590-473d-8dad-6f5de04b7d74.png">|<img width="770" alt="image" src="https://user-images.githubusercontent.com/5528307/218062544-2926c07a-b52a-47b3-aea9-163660f8f0c5.png">|

**Comment by Palanikannan1437** [comment]
This is definitely a priority I'm trying to work on and is tracked at #11 

But to make your life a bit easier by removing Step-1, you could perform it by following these steps

1. You could avoid Step-1 by setting up a custom Hotkey for the "Open in Gitpod" command like so,

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/73993394/218109284-539e22b4-5c03-4daa-9723-8d0ff4ebbc3f.png">

2. Now when you hit the custom hotkey (in my case CMD+Shift+i), you directly would be able to see the recently visited repositories....PS: The contexts of these visited repositories open really quick since we've cached them 😉
 
![cache-recentrepos](https://user-images.githubusercontent.com/73993394/218110432-8a37af9a-d8e2-4337-86e7-e2d0bca1ed86.gif)

Please let me know if this helps 😄

**Comment by Palanikannan1437** [comment]
Being tracked at #9

**Comment by Palanikannan1437** [comment]
Being tracked at #9
